import time
import random
from selenium.webdriver.common.action_chains import ActionChains
from random import gauss

def Animation1(driver):
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    driver.execute_script("window.scrollTo(0, 2000)") 
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 15000))/1000)
    driver.execute_script("window.scrollTo(0, 200)")
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)") 
    time.sleep(abs((gauss(1, 1) * 500 + 13000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 200)")
    time.sleep(abs((gauss(1, 1) * 500 + 14000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    menu_list = ["NEW ARRIVALS","E-LIQUIDS","DEVICES","E-LIQUIDS","ALL BRANDS","DEALS & SALE","CONTACT US","HOME"]
    menu_item_1 = random.choice(menu_list)
    print(menu_item_1)
    time.sleep(abs((gauss(1, 1) * 500 + 7000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='{menu_item_1}']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    menu_item_2 = random.choice(menu_list)
    print(menu_item_2)
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='{menu_item_2}']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)

def Animation2(driver):
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, 1000)")
    time.sleep(3)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li").click()
    time.sleep(50)
    canvas = driver.find_element_by_css_selector("body")
    time.sleep(10)
    action = ActionChains(driver)
    time.sleep(10)
    action.move_to_element(canvas)
    #time.sleep(5)
    action.click_and_hold()
    action.move_by_offset(8,1)
    action.move_by_offset(6,1)
    action.move_by_offset(4,1)
    action.move_by_offset(2,1)
    action.move_by_offset(1,1)
    action.move_by_offset(1,2)
    action.move_by_offset(1,4)
    action.move_by_offset(1,6)
    action.move_by_offset(1,8)
    time.sleep(5)
    action.release()
    action.perform() 
    time.sleep(25) 
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[2]").click() 
    time.sleep(10)
    driver.execute_script("window.scrollTo(1000, 0)") 
    time.sleep(17)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[2]/div/div/div/h2/a/button").click()
    time.sleep(15) 
    driver.execute_script("window.scrollTo(1000, 0)") 
    time.sleep(15)                
    driver.find_element_by_xpath("//div[@id='shopify-section-collection-template']/section/div[3]/div/div/button[2]").click() 
    time.sleep(15)
    driver.find_element_by_xpath("//div[@id='bc-sf-filter-top-sorting']/button[2]").click() 
    time.sleep(15)
    driver.execute_script("window.scrollTo(0, 1000)") 
    time.sleep(15)    
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='//*[@id='section-header']/div/div[1]/button']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)

def Animation3(driver):
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, 1000)")
    time.sleep(3)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[4]").click()
    time.sleep(15) 
    driver.execute_script("window.scrollTo(0, 1300)")
    time.sleep(10)
    driver.execute_script("window.scrollTo(0, 900)") 
    time.sleep(10)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[3]").click()
    time.sleep(3) 
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/div/div[3]/p/span").click() 
    time.sleep(10)  
    canvas = driver.find_element_by_css_selector("body")
    time.sleep(1)
    action = ActionChains(driver)
    time.sleep(1)
    action.move_to_element(canvas)
    #time.sleep(5)
    action.click_and_hold()
    action.move_by_offset(8,1)
    action.move_by_offset(6,1)
    action.move_by_offset(4,1)
    action.move_by_offset(2,1)
    action.move_by_offset(1,1)
    action.move_by_offset(1,2)
    action.move_by_offset(1,4)
    action.move_by_offset(1,6)
    action.move_by_offset(1,8)
    time.sleep(5)
    action.release()
    action.perform() 
    time.sleep(15)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(10)                 
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[2]/div/div/div/h2/a/button").click() 
    time.sleep(10)                                
    driver.find_element_by_xpath("//div[@id='shopify-section-collection-template']/section/div[3]/div/div/button[2]").click()
    time.sleep(10)                
    driver.find_element_by_xpath("//div[@id='bc-sf-filter-top-sorting']/button[6]").click()  
    time.sleep(10)                
    driver.find_element_by_xpath("//div[2]/div/div/div/h3/span").click() 
    time.sleep(10)                
    driver.find_element_by_xpath("//div[2]/div/div[2]/div/h3/span").click()
    time.sleep(10)  
    driver.execute_script("window.scrollTo(0, 1000)") 
    time.sleep(10)  
    driver.execute_script("//header[@id='section-header']/div/div/nav/ul/li[1]/a") 
    time.sleep(10)      
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='//*[@id='section-header']/div/div[1]/button']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)


def Animation5(driver):
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, 1000)")
    time.sleep(3)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[3]").click()
    time.sleep(3)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/div/div[3]/p/span").click() 
    time.sleep(10)  
    canvas = driver.find_element_by_css_selector("body")
    time.sleep(1)
    action = ActionChains(driver)
    time.sleep(1)
    action.move_to_element(canvas)
    #time.sleep(5)
    action.click_and_hold()
    action.move_by_offset(8,1)
    action.move_by_offset(6,1)
    action.move_by_offset(4,1)
    action.move_by_offset(2,1)
    action.move_by_offset(1,1)
    action.move_by_offset(1,2)
    action.move_by_offset(1,4)
    action.move_by_offset(1,6)
    action.move_by_offset(1,8)
    time.sleep(5)
    action.release()
    action.perform() 
    time.sleep(15) 
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[4]").click()
    time.sleep(15) 
    driver.execute_script("window.scrollTo(0, 1300)")
    time.sleep(10)
    driver.execute_script("window.scrollTo(0, 10)") 
    time.sleep(10)                
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[2]/div/div/div/h2/a/button").click() 
    time.sleep(10)                
    driver.find_element_by_xpath("//div[2]/div/div/div/h3/span").click() 
    time.sleep(10)                
    driver.find_element_by_xpath("//div[2]/div/div[2]/div/h3/span").click() 
    time.sleep(10)                
    driver.find_element_by_xpath("//div[@id='shopify-section-collection-template']/section/div[3]/div/div/button[2]").click()
    time.sleep(10)                
    driver.find_element_by_xpath("//div[@id='bc-sf-filter-top-sorting']/button[8]").click()  
    time.sleep(10) 
    driver.execute_script("window.scrollTo(0, 1000)") 
    time.sleep(10) 
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='//*[@id='section-header']/div/div[1]/button']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)

def Animation6(driver):
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    time.sleep(1)
    driver.execute_script("window.scrollTo(0, 1000)")
    time.sleep(3)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li").click()
    time.sleep(3)
    canvas = driver.find_element_by_css_selector("body")
    time.sleep(1)
    action = ActionChains(driver)
    time.sleep(1)
    action.move_to_element(canvas)
    #time.sleep(5)
    action.click_and_hold()
    action.move_by_offset(8,1)
    action.move_by_offset(6,1)
    action.move_by_offset(4,1)
    action.move_by_offset(2,1)
    action.move_by_offset(1,1)
    action.move_by_offset(1,2)
    action.move_by_offset(1,4)
    action.move_by_offset(1,6)
    action.move_by_offset(1,8)
    time.sleep(5)
    action.release()
    action.perform() 
    time.sleep(10)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[3]/div/div[2]/ul/li[2]").click() 
    time.sleep(3)
    canvas = driver.find_element_by_css_selector("body")
    time.sleep(1)
    action = ActionChains(driver)
    time.sleep(1)
    action.move_to_element(canvas)
    #time.sleep(5)
    action.click_and_hold()
    action.move_by_offset(8,1)
    action.move_by_offset(6,1)
    action.move_by_offset(4,1)
    action.move_by_offset(2,1)
    action.move_by_offset(1,1)
    action.move_by_offset(1,2)
    action.move_by_offset(1,4)
    action.move_by_offset(1,6)
    action.move_by_offset(1,8)
    time.sleep(20)
    action.release()
    action.perform() 
    time.sleep(20) 
    driver.execute_script("window.scrollTo(1000, 0)") 
    time.sleep(20)
    driver.find_element_by_xpath("//div[@id='shopify-section-product-template']/section/div/div[2]/div/div/div/h2/a/button").click()
    time.sleep(30) 
    driver.execute_script("window.scrollTo(1000, 0)") 
    time.sleep(30)                
    driver.find_element_by_xpath("//div[@id='shopify-section-collection-template']/section/div[3]/div/div/button[2]").click() 
    time.sleep(30)
    driver.find_element_by_xpath("//div[@id='bc-sf-filter-top-sorting']/button[6]").click() 
    time.sleep(40)
    driver.execute_script("window.scrollTo(0, 1000)") 
    time.sleep(40)   
    try:
        driver.find_element_by_id("vjd_age_agree").click()
    except:
        pass
    driver.execute_script("window.scrollTo(0, 2000)") 
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 20000))/1000)
    driver.execute_script("window.scrollTo(0, 200)")
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)") 
    time.sleep(abs((gauss(1, 1) * 500 + 20000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 30000))/1000)
    driver.execute_script("window.scrollTo(0, 200)")
    time.sleep(abs((gauss(1, 1) * 500 + 20000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    menu_list = ["NEW ARRIVALS","E-LIQUIDS","DEVICES","E-LIQUIDS","ALL BRANDS","DEALS & SALE","CONTACT US","HOME"]
    menu_item_1 = random.choice(menu_list)
    print(menu_item_1)
    time.sleep(abs((gauss(1, 1) * 500 + 7000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='{menu_item_1}']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    menu_item_2 = random.choice(menu_list)
    print(menu_item_2)
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    try:
        driver.find_element_by_xpath('//*[@id="section-header"]/div/div[1]/button').click()
    except:
        pass
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.find_element_by_xpath(f"//a[text()='//*[@id='section-header']/div/div[1]/button']").click()
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 2000)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)
    driver.execute_script("window.scrollTo(0, 20)")
    time.sleep(abs((gauss(1, 1) * 500 + 5000))/1000)