domain: vapejuicedepot.com
tld: com
devices:
- user_agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_2_3 like Mac OS X) AppleWebKit/605.1.15
    (KHTML, like Gecko) Version/13.0.3 Mobile/15E148 Safari/604.1
  window_size: 375,812
  mobile: true
- user_agent: Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML,
    like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1
  window_size: 768,1024
  mobile: true
ports:
- 4445
- 4446
- 4447
- 4448
- 4449
- 4450
- 4451
- 4452
- 4453
- 4454
- 4455
- 4456
- 4457
- 4458
- 4459
- 4460
- 4461
- 4462
- 4463
- 4464
